version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myPayload"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q62n8o8somya"
s3_prefix = "myPayload"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=159292040131.dkr.ecr.us-east-1.amazonaws.com/mycloudformationstack3ede8fe3/helloworldfunction19d43fc4repo"]
